const TRANSPORT_REQUEST_STATUS = Object.freeze({
  PENDING: "pending",
  ACCEPTED_BY_TRANSPORTER: "accepted_by_transporter",
  CONFIRMED: "confirmed",
  CANCELLED: "cancelled",
  EXPIRED: "expired",
  DELIVERED: "delivered",
});

// Kept only so old saved documents using the previous status still work.
const LEGACY_ACCEPTED_STATUS = "accepted";

const TRANSPORT_REQUEST_STATUS_VALUES = Object.freeze(Object.values(TRANSPORT_REQUEST_STATUS));

const TRANSPORTER_VISIBLE_STATUSES = Object.freeze([
  TRANSPORT_REQUEST_STATUS.CONFIRMED,
  TRANSPORT_REQUEST_STATUS.DELIVERED,
]);

const TRACKABLE_STATUSES = Object.freeze([
  TRANSPORT_REQUEST_STATUS.CONFIRMED,
  TRANSPORT_REQUEST_STATUS.DELIVERED,
]);

const DELIVERABLE_STATUSES = Object.freeze([
  TRANSPORT_REQUEST_STATUS.CONFIRMED,
]);

const CLIENT_CONFIRM_STATUSES = Object.freeze([
  LEGACY_ACCEPTED_STATUS,
  TRANSPORT_REQUEST_STATUS.ACCEPTED_BY_TRANSPORTER,
]);

module.exports = {
  TRANSPORT_REQUEST_STATUS,
  TRANSPORT_REQUEST_STATUS_VALUES,
  TRANSPORTER_VISIBLE_STATUSES,
  TRACKABLE_STATUSES,
  DELIVERABLE_STATUSES,
  CLIENT_CONFIRM_STATUSES,
  LEGACY_ACCEPTED_STATUS,
};
